### PR TITLE
00-spatio-temporal tutorial updates: YAML, alt text, and a lot of URLs

### PR DESCRIPTION
**Pull request by adernbach**
Hey, @donal-at-NEON . The first spatio-temporal tutorial is done! I made some comments in the code about a few links that I updated but I wasn't 100% sure if they made the most sense. 

Also, there's a youtube video on line 483 that doesn't seem to be relevant. Should it be this video: https://www.youtube.com/watch?v=m7SXoFv6Sdc? 

Let me know if you have any questions!

### CODE REVIEW

**Comment by mjones01** [comment]
@adernbach & @donal-at-NEON - great catch on the video! It looks like the series was linked instead of the specific video and the series has been updated with newer videos.  
I'd recommend using the *How Does LiDAR Remote Sensing Work?* video instead of  *LiDAR - Introduction to Light Detection and Ranging*: https://youtu.be/EYbhNSUnIdU . 
Thanks .

**Comment by adernbach** [comment]
Thanks for the recommendation @mjones01 ! I updated the Youtube link.

**Comment by adernbach** [comment]
Hey @donal-at-NEON , I realized that I missed the %_includes for the wd gray box. Let me know if you'd like me to update that.

**Comment by adernbach** [comment]
@donal-at-NEON , I commented in the 02-spatio code about a couple updates I made. I left a few other things alone but still want to direct your attention to them: 
- [29] I don't know what `%includes` this is
- [146] and [378] This looks weird: `{: .notice}`
- [385] I'm not sure how this is supposed to be linked because it's not a specific HDF5 tutorial

**Comment by adernbach** [comment]
Hey @donal-at-NEON, I've incorporated your comments into the 00 and 02 tutorials. Let me know if there are any other changes to make!

**Pull request merged**
